services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
        DATABASE_URL: ${DATABASE_URL}

    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5430:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  data:

networks:
  app-network:
    driver: bridge
