services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5430:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: